#version: '3.8'

services:
  main-script:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py

  training-script:
    build:
      context: .
      dockerfile: Dockerfile.training
    command: python3 training.py
