#version: '3.8'

services:
  main-script:
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 main.py

#  app-script:
#    build:
#      context: .
#      dockerfile: Dockerfile.app
#    command: python3 app.py
