XG_Boost:
    n_estimators: 200
    max_depth: 10
    learning_rate : 0.3
    subsample: 1.0
    colsample_bytree: 0.9


#base_score=0.5, booster='gbtree',
                #                               n_estimators=200,
                #                               # early_stopping_rounds=50,
                #                               objective='reg:squarederror',
                #                               max_depth=6,
                #                               learning_rate=0.01,
                #                                min_child_weight=1,
                #                               subsample=0.8,
                #                               colsample_bytree=0.8,
                #                               gamma=0,
                #                               reg_alpha=0,
                #                               reg_lambda=1